<?php

namespace AppBundle\Repository;

/**
 * LoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoggerRepository extends \Doctrine\ORM\EntityRepository
{
}
